server:
  servlet:
    context-path: /
  port: 9999
spring:
  profiles:
    active: dev
  application:
    name: datasource-nacos
# sentinel dashboard
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            rule-type: flow